### ISSUE TITLE
I can not use the repo

### ISSUE THREAD

**Issue by COPS95** [bonnybabukachappilly/ros2bridge#2]
I was trying to install but i got error.
First: when i try to install, the installation is not completed with all folder
Second: I had problem with interpreter python
Can you help men, please

**Comment by bonnybabukachappilly** [comment]
Sorry for the late replay. Could you share some more info.

**Comment by COPS95** [comment]
i didn't know which was the problem, finally i find another solution for my problem, and not use this one. thanks!

**Comment by bonnybabukachappilly** [comment]
Ok, Without having any details how can I address the issue?
